In [40]:
import pandas as pd
import numpy as np

In [41]:
df = pd.read_csv("../data/raw/2026-01-01.csv")

df.head()

,date,serial_number,model,capacity_bytes,failure,datacenter,cluster_id,vault_id,pod_id,pod_slot_num,...,smart_250_normalized,smart_250_raw,smart_251_normalized,smart_251_raw,smart_252_normalized,smart_252_raw,smart_254_normalized,smart_254_raw,smart_255_normalized,smart_255_raw
0,2026-01-01,000a43e7dee60010,DELLBOSS VD,480036847616,0,ams5,31,2017,5,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2026-01-01,00ac486b9bec0010,DELLBOSS VD,480036847616,0,ams5,31,2013,16,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2026-01-01,01b776caeb6a0010,DELLBOSS VD,480036847616,0,ams5,31,2014,11,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2026-01-01,02308a3415be0010,DELLBOSS VD,480036847616,0,ams5,31,2007,4,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2026-01-01,0394cd7bc5d00010,DELLBOSS VD,480036847616,0,ams5,31,2017,4,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [42]:
df.shape

(338760, 197)

In [43]:
df['serial_number'].nunique()

338760

In [44]:
df['model'].nunique()

78

In [45]:
df['model'].value_counts().head(10)

model
WDC WUH722222ALE6L4     44265
TOSHIBA MG08ACA16TA     39440
TOSHIBA MG07ACA14TA     37198
ST16000NM001G           34334
WDC WUH721816ALE6L4     26310
ST12000NM0008           18534
TOSHIBA MG10ACA20TE     17943
ST8000NM0055            13183
ST12000NM001G           13148
HGST HUH721212ALE604    13118
Name: count, dtype: int64

In [46]:
df[df['failure'] == 1]

,date,serial_number,model,capacity_bytes,failure,datacenter,cluster_id,vault_id,pod_id,pod_slot_num,...,smart_250_normalized,smart_250_raw,smart_251_normalized,smart_251_raw,smart_252_normalized,smart_252_raw,smart_254_normalized,smart_254_raw,smart_255_normalized,smart_255_raw
253508,2026-01-01,ZHZ3X3YY,ST12000NM0008,12000138625024,1,sac0,0,1131,13,19.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [47]:
missing_percent = df.isna().mean() * 100 
missing_percent = missing_percent.sort_values()

missing_percent

date                      0.0
serial_number             0.0
model                     0.0
capacity_bytes            0.0
failure                   0.0
                        ...
smart_251_raw           100.0
smart_251_normalized    100.0
smart_250_raw           100.0
smart_255_normalized    100.0
smart_255_raw           100.0
Length: 197, dtype: float64

In [48]:
import os
import pandas as pd

folder = "../data/raw"
files = os.listdir(folder)

total_rows = 0
non_missing_totals = None

for file in files:
    if not file.endswith(".csv"):
        continue

    file_path = os.path.join(folder, file)
    current_df = pd.read_csv(file_path)

    current_counts = current_df.notna().sum()

    if non_missing_totals is None:
        non_missing_totals = current_counts
    else:
        non_missing_totals = non_missing_totals.add(
            current_counts,
            fill_value=0
        )

    total_rows += len(current_df)

In [51]:
availability_percent = (non_missing_totals / total_rows) * 100
availability_percent = availability_percent.sort_values(ascending=False)
availability_percent = availability_percent[availability_percent > 80]

availability_percent

date                    100.000000
serial_number           100.000000
model                   100.000000
capacity_bytes          100.000000
failure                 100.000000
datacenter              100.000000
cluster_id              100.000000
vault_id                100.000000
pod_id                  100.000000
is_legacy_format        100.000000
smart_12_normalized      99.871172
smart_9_normalized       99.871172
smart_9_raw              99.871172
smart_12_raw             99.871172
smart_194_raw            99.869408
smart_194_normalized     99.869408
smart_1_normalized       99.777779
smart_1_raw              99.777779
smart_192_normalized     99.544234
smart_192_raw            99.544234
smart_5_normalized       99.325343
smart_5_raw              99.325343
smart_199_normalized     99.324944
smart_199_raw            99.324944
smart_198_normalized     99.231577
smart_198_raw            99.231577
smart_4_raw              98.998405
smart_3_raw              98.998405
smart_3_normalized       98.998405
smart_7_normalized       98.998405
smart_7_raw              98.998405
smart_4_normalized       98.998405
smart_193_raw            98.981737
smart_193_normalized     98.981737
pod_slot_num             98.764042
smart_197_raw            97.494304
smart_197_normalized     97.494304
smart_10_normalized      97.378840
smart_10_raw             97.378840
dtype: float64